module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class", //false or 'media'
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      white: "#FFFFFF",
      "whatsApp-green": "#25D366",
      "dark-call-sec": "#FFFFFF",
      "dark-accent": "#2F3136",
      "dark-sec": "#36393F",
      "dark-bg": "#202225",
      "light-accent": "#9d9d9d",
      "light-bg": "#FFFFFF",
      "light-call-sec": "#5063F0",
      "light-hover": "#c9c7c7",
      "light-text-small": "#808080",
      "dark-hover": "#17171c",
      "call-primary": "#E91E63",
      "output-error": "#DC143C",
      "output-green": "#4BB543",
      "grey-end": "#232526",
      "grey-start": "#414345",
      "light-grey-start": "#7D7D7D",
      "light-grey-end": "#696969",
      "modal-bg": "#c8c8c8",
      "yellow-start": "#F3CA5A",
      "yellow-end": "#D8A38E",
      "purple-bg": "#CD92A4",
      "green-bg": "#38CB97",
      "blue-bg": "#0FBEFA",
      "dark-white": "#E5E5E5",
      "blue-green": "#75E6DA",
      "dark-red": "#BE0A00",
      "dark-black": "#000000",
    },

    extend: {},
  },
  plugins: [],
};
